import './globals.css';
import { Inter } from 'next/font/google';
import Header from './components/Header';
import AuthProvider from './context/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-slate-100`}>
				<AuthProvider>
					<Header />
					{children}
				</AuthProvider>
			</body>
		</html>
	);
}
